package scanner

import "testing"

func TestCleanFirstMessage(t *testing.T) {
	cases := []struct{ name, in, want string }{
		{"plain", "これHPだけどさ、Git管理した方が良くない？", "これHPだけどさ、Git管理した方が良くない？"},
		{"command wrapper with args",
			"<command-message>backup-update</command-message>\n<command-name>/backup-update</command-name>\n<command-args>Memberprofile</command-args>",
			"/backup-update Memberprofile"},
		{"command wrapper no args", "<command-name>/handover</command-name>", "/handover"},
		{"control command clear skipped", "<command-name>/clear</command-name>", ""},
		{"control command effort with args skipped", "<command-name>/effort</command-name>\n<command-args>high</command-args>", ""},
		{"resume marker skipped", "Resume coding session a4b1c36f-1237-4f61-ba6e-cec48edf98bc", ""},
		{"command name without slash", "<command-name>rinko</command-name>", "/rinko"},
		{"hello memory recovers user_request",
			"Hello memory agent, here is context.\n<user_request>あ、よかった レポジトリはプライベートだったのね</user_request>\ntrailing",
			"あ、よかった レポジトリはプライベートだったのね"},
		{"hello memory no request", "Hello memory agent, blah blah context only", ""},
		{"progress checkpoint", "PROGRESS SUMMARY CHECKPOINT\n===========================\nWrite progress notes of what was done", ""},
		{"separator only", "===========================", ""},
		{"compaction prompt", "Your task is to create a detailed summary of the conversation so far, paying close attention", ""},
		{"suggestion mode", "[SUGGESTION MODE: Suggest what the user might naturally type next]", ""},
		{"caveat", "Caveat: The messages below were generated by the user", ""},
		{"absolute path is not a slash command", "/Users/eiyuto/Documents/call-md-ja を確認して", "/Users/eiyuto/Documents/call-md-ja を確認して"},
		{"system reminder stripped", "<system-reminder>無視して</system-reminder> 本当の依頼です", "本当の依頼です"},
		{"comparison operators preserved", "a < b と c > d を比較して", "a < b と c > d を比較して"},
		{"multiline code preserved", "コードを直して:\nif a < b {\n  return a > 0\n}", "コードを直して: if a < b { return a > 0 }"},
		{"genuine stray tag stripped", "<user_request>本文だけ残す</user_request>", "本文だけ残す"},
		{"observed primary block, no request", "<observed_from_primary_session><what_happened>Edit foo.js</what_happened></observed_from_primary_session>", ""},
		{"empty", "   ", ""},
	}
	for _, c := range cases {
		if got := cleanFirstMessage(c.in); got != c.want {
			t.Errorf("%s:\n  cleanFirstMessage(%q)\n  = %q\n  want %q", c.name, c.in, got, c.want)
		}
	}
}
